language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y scons

before_script:
  - git clone https://github.com/xanthospap/ggdatetime.git && cd ggdatetime
  - sudo scons install
  - cd ../
  - git clone https://github.com/xanthospap/ggeodesy.git && cd ggeodesy
  - sudo scons install
  - sudo ldconfig
  - cd ../

script:
  - scons
  - scons debug=1
